services:
    web:
        build: .
        # command: python /code/manage.py runserver 0.0.0.0:8000
        command: gunicorn things_api_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
        volumes:
            - .:/code
        ports:
            - 8000:8000
# add back in for postgres
#         depends_on:
#             - db

#     db:
#         image: postgres:14
#         volumes:
#             - postgres_data:/var/lib/postgresql/data/
#         environment:
#             - "POSTGRES_HOST_AUTH_METHOD=trust"

# volumes:
#   postgres_data:
